### ISSUE TITLE
Doubled content for the page alias

### ISSUE THREAD

**Issue by tastethecake** [wschwaiger/qwat-ser-preview#2]
The extension shows the page alias twice, with the first missing it’s last letter. See attached image for better description ;)
![issue](https://cloud.githubusercontent.com/assets/22492667/18905496/b0e4cf06-8563-11e6-9120-1428de632430.gif)

**Comment by wschwaiger** [comment]
Hmm. I am afraid I can not reproduce the behavior you are referring to. Can you send me please the settings you have for the URL under SETTINGS in Contao?

**Comment by tastethecake** [comment]
I have this behaviour on two Contao installations. 

Are these the settings you mean?
![url](https://cloud.githubusercontent.com/assets/22492667/19114962/7c7af346-8b10-11e6-9077-19666d610987.gif)

**Comment by wschwaiger** [comment]
exactly. thank you. I see that you do not use a url-suffix. which is most likely the source of the problem. I'll look into it.

**Comment by wschwaiger** [comment]
This should be fixed. Please update the extension to 1.0.1. Thanks for finding this.

**Comment by tastethecake** [comment]
Great, it works! Thanks a lot!
